package com.mkdirchip.tilt.data

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

@Dao
interface TilDao {

    // ---- reads -------------------------------------------------------------

    /** Null bounds mean "unbounded", which is how the All preset is expressed. */
    @Transaction
    @Query(
        """
        SELECT * FROM entries
        WHERE (:start IS NULL OR localDate >= :start)
          AND (:end IS NULL OR localDate <= :end)
        ORDER BY createdAtEpochMillis DESC
        """
    )
    fun observeEntries(start: String?, end: String?): Flow<List<TilEntryWithLabels>>

    /**
     * Same as [observeEntries] but restricted to entries carrying any of [labelIds]. Kept as a
     * separate query because Room renders an empty list as `IN ()`, which SQLite rejects when
     * the statement is prepared — a guard in the WHERE clause would not save it.
     */
    @Transaction
    @Query(
        """
        SELECT * FROM entries
        WHERE (:start IS NULL OR localDate >= :start)
          AND (:end IS NULL OR localDate <= :end)
          AND id IN (SELECT entryId FROM entry_labels WHERE labelId IN (:labelIds))
        ORDER BY createdAtEpochMillis DESC
        """
    )
    fun observeEntriesWithAnyLabel(
        start: String?,
        end: String?,
        labelIds: List<Long>,
    ): Flow<List<TilEntryWithLabels>>

    @Transaction
    @Query("SELECT * FROM entries WHERE id = :id")
    suspend fun findEntry(id: Long): TilEntryWithLabels?

    /** Only labels attached to at least one entry, which is what filtering may offer. */
    @Query(
        """
        SELECT l.* FROM labels l
        INNER JOIN entry_labels el ON el.labelId = l.id
        GROUP BY l.id
        ORDER BY l.displayName COLLATE NOCASE ASC
        """
    )
    fun observeLabelsInUse(): Flow<List<LabelEntity>>

    @Query("SELECT DISTINCT localDate FROM entries ORDER BY localDate ASC")
    fun observeActiveDates(): Flow<List<String>>

    @Query("SELECT localDate, COUNT(*) AS count FROM entries GROUP BY localDate ORDER BY localDate ASC")
    fun observeDateCounts(): Flow<List<DateCount>>

    @Query("SELECT COUNT(*) FROM entries WHERE localDate >= :start AND localDate <= :end")
    fun observeEntryCount(start: String, end: String): Flow<Int>

    @Query("SELECT COUNT(DISTINCT localDate) FROM entries WHERE localDate >= :start AND localDate <= :end")
    fun observeActiveDayCount(start: String, end: String): Flow<Int>

    @Query("SELECT * FROM entries ORDER BY RANDOM() LIMIT 1")
    suspend fun randomEntry(): TilEntryEntity?

    @Query("SELECT COUNT(*) FROM entries")
    suspend fun entryCount(): Int

    // ---- writes ------------------------------------------------------------

    @Insert
    suspend fun insertEntry(entry: TilEntryEntity): Long

    @Update
    suspend fun updateEntry(entry: TilEntryEntity)

    @Delete
    suspend fun deleteEntry(entry: TilEntryEntity)

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertLabel(label: LabelEntity): Long

    @Query("SELECT * FROM labels WHERE name = :name")
    suspend fun findLabelByName(name: String): LabelEntity?

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertCrossRef(ref: EntryLabelCrossRef)

    @Query("DELETE FROM entry_labels WHERE entryId = :entryId")
    suspend fun clearLabelsOf(entryId: Long)

    /** Implements "a label with no entries stops being offered" without a cleanup pass. */
    @Query("DELETE FROM labels WHERE id NOT IN (SELECT labelId FROM entry_labels)")
    suspend fun deleteOrphanedLabels()

    // ---- composite writes --------------------------------------------------

    /**
     * Inserts an entry and attaches [labels]. An [TilEntryEntity.id] of 0 is autogenerated; a
     * non-zero id is preserved, which is how an undone deletion comes back as the same entry.
     */
    @Transaction
    suspend fun insertEntryWithLabels(entry: TilEntryEntity, labels: List<LabelEntity>): Long {
        val entryId = insertEntry(entry)
        val resolvedId = if (entry.id != 0L) entry.id else entryId
        attachLabels(resolvedId, labels)
        deleteOrphanedLabels()
        return resolvedId
    }

    @Transaction
    suspend fun updateEntryWithLabels(entry: TilEntryEntity, labels: List<LabelEntity>) {
        updateEntry(entry)
        clearLabelsOf(entry.id)
        attachLabels(entry.id, labels)
        deleteOrphanedLabels()
    }

    @Transaction
    suspend fun deleteEntryAndPruneLabels(entry: TilEntryEntity) {
        deleteEntry(entry)
        deleteOrphanedLabels()
    }

    /** Resolves each label to an existing row or creates it, then links it to the entry. */
    suspend fun attachLabels(entryId: Long, labels: List<LabelEntity>) {
        for (label in labels) {
            val inserted = insertLabel(label)
            val labelId = if (inserted != -1L) inserted else findLabelByName(label.name)?.id
            if (labelId != null) insertCrossRef(EntryLabelCrossRef(entryId, labelId))
        }
    }
}
